export default {
	ACTION_TYPES: {
		INCREMENT: 'INCREMENT',
		DECREMENT: 'DECREMENT',
		UPDATE_EQUATION: 'UPDATE_EQUATION',
		REMOVE_VALUE: 'REMOVE_VALUE',
		CLEAR_VALUE: 'CLEAR_VALUE',
		SET_EXTREMES: 'SET_EXTREMES',
		DRAW_GRAPH: 'DRAW_GRAPH',
	}
};
